### ISSUE TITLE
Dump of pair vtk file

### ISSUE THREAD

**Issue by yfun0815** [ParticulateFlow/LIGGGHTS-PFM#12]
Hi,
In previous LIGGGHTS, this is a dump pair/gran/vtk command to dump the information about pair force or something. If there is still such a function in the latest version of LIGGGHTS-PFM? Thanks!
Sincerely,
Fan

**Comment by danielque** [comment]
_dump pair/gran/vtk_ is not available in our version (it was added to LIGGGHTS-PUBLIC after our version was forked off and has never been backported). However, _dump local_ should provide similar functionality with the exception that it writes the data to simple text files instead of vtk files.
See, for example, the usage [here](https://github.com/ParticulateFlow/LIGGGHTS-PFM/blob/9f7281aad2754a308219fc5019c911c2a1f3cc96/examples/LIGGGHTS/PFM/tests/contact_models/chung/test01/in.elastic_normal_impact_2_spheres) for contact forces:
https://github.com/ParticulateFlow/LIGGGHTS-PFM/blob/9f7281aad2754a308219fc5019c911c2a1f3cc96/examples/LIGGGHTS/PFM/tests/contact_models/chung/test01/in.elastic_normal_impact_2_spheres#L130-L134
or [here](https://github.com/ParticulateFlow/LIGGGHTS-PFM/blob/9f7281aad2754a308219fc5019c911c2a1f3cc96/examples/LIGGGHTS/Tutorials_public/bondspackage/sphere/in.bonds) for bond properties:
https://github.com/ParticulateFlow/LIGGGHTS-PFM/blob/9f7281aad2754a308219fc5019c911c2a1f3cc96/examples/LIGGGHTS/Tutorials_public/bondspackage/sphere/in.bonds#L87-L88

**Comment by yfun0815** [comment]
I understood. Thank you very much.
